quarkus:
  application:
    name: RandomThoughts
  http:
    port: ${API_PORT}
    cors:
      ~: true
      origins: ${CORS_ORIGINS}
      methods: ${CORS_METHODS}
      headers: "Content-Type, Accept, X-Requested-With, remember-me"
      access-control-max-age: "3600"
      access-control-allow-credentials: true
  log:
    level: "INFO"
    console:
      enable: true
  datasource:
    db-kind: postgresql
    username: ${DB_USER}
    password: ${DB_PWD}
    jdbc:
      url: jdbc:postgresql://${DB_HOST}/${DB_SCHEMA}
  hibernate-orm:
    database:
      generation: 
        ~: update
